### PR TITLE
Cover rework

### PR DESCRIPTION
**Pull request by johnch18**
An attempt to rework covers with the ISerializedObject model. Changed over the controller cover, but the GUI on it doesn't work for some reason. Need some eyes on this

### CODE REVIEW

**Comment by botn365** [comment]
why rename gt_coverBehaviour when nothing even replaces it
and instead of renaming the old just give the new one a difrent name

**Comment by johnch18** [comment]
Because the default `int` behavior is referenced as legacy throughout the code and is being deprecated already

**Comment by botn365** [comment]
but that will break other mods that use GT_CoverBehavior
you can mark it as depricated but no name change of somthing that is public

**Comment by johnch18** [comment]
Dammit I didn't even consider that, my bad

**Comment by Houstonruss** [comment]
What do you mean other mods

**Comment by botn365** [comment]
obama

**Comment by johnch18** [comment]
It works now, and I fixed some other covers by fixing a bug in `GT_Proxy`

**Review by botn365 — APPROVED** [review]
LGTM

**Pull request merged**
